pipeline {
    agent any

    environment {
        IMAGE_NAME = "pradeepm1208/new_practice:backend"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Pradeep-ECE/MERN-Chat-App-Phase-2.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Skipping tests...'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Docker Run') {
            steps {
                sh 'docker run -d -p 5000:5000 --name chat-app $IMAGE_NAME'
            }
        }
    }
}
