pipeline {
    agent any

    tools {
        nodejs "Node20"
    }

    environment {
        DOCKER_HOST = "unix:///var/run/docker.sock"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Pradeep-ECE/MERN-Chat-App-Phase-2.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('server') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('server') {
                    sh 'npm test || true'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('server') {
                    sh 'docker build -t chat-backend .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                sh 'docker run -d -p 4000:4000 chat-backend'
            }
        }
    }
}
