pipeline {
    agent any

    tools {
        nodejs "Node20"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Pradeep-ECE/MERN-Chat-App-Phase-2.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('server') {
                    'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('server') {
                    'npm test || true'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('server') {
                    docker build -t chat-backend .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                'docker run -d -p 4000:4000 chat-backend'
            }
        }
    }
}
